/*
 * Messages.ts
 *
 * Original SweetHomeJS code, Copyright (c) 2026 SweetHomeJS contributors
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

/**
 * Messages (task 7.5): the i18n runtime. Loads the JSON bundles generated by
 * tools/i18n/build-messages.mjs and resolves keys with Java's locale fallback
 * chain (base ← _lang ← _lang_country). Registered as the core's message
 * registry so UserPreferences.getLocalizedString works app-wide.
 */
import { setMessageRegistry } from "@sweethomejs/core";
import baseMessages from "./messages.json" with { type: "json" };
import frMessages from "./messages_fr.json" with { type: "json" };
import deMessages from "./messages_de.json" with { type: "json" };
import esMessages from "./messages_es.json" with { type: "json" };
import itMessages from "./messages_it.json" with { type: "json" };
import ptMessages from "./messages_pt.json" with { type: "json" };
import nlMessages from "./messages_nl.json" with { type: "json" };
import ruMessages from "./messages_ru.json" with { type: "json" };

type Bundle = Record<string, Record<string, string>>;

const BUNDLES: Record<string, Bundle> = {
  en: baseMessages as Bundle,
  fr: frMessages as Bundle,
  de: deMessages as Bundle,
  es: esMessages as Bundle,
  it: itMessages as Bundle,
  pt: ptMessages as Bundle,
  nl: nlMessages as Bundle,
  ru: ruMessages as Bundle,
};

/** The supported locales (top-8, first is the default). */
export const SUPPORTED_LOCALES = Object.keys(BUNDLES);

/**
 * Resolves a message with the fallback chain. `bundleName` is the controller
 * class name (e.g. "HomeController") as produced by the core's
 * getLocalizedString; the key is the message key.
 */
export function getLocalizedString(bundleName: string, key: string, locale: string): string | null {
  const [lang, country] = locale.split("-");
  const langCode = lang ?? "";
  const candidates = [baseMessages as Bundle, BUNDLES[langCode] ?? {}, country !== undefined ? (BUNDLES[langCode + "-" + country] ?? {}) : {}];
  for (const bundle of candidates) {
    const classMessages = bundle[bundleName];
    if (classMessages !== undefined) {
      const value = classMessages[key];
      if (value !== undefined) {
        return value;
      }
    }
  }
  return null;
}

let currentLocale = "en";

/** Returns the current locale. */
export function getLocale(): string {
  return currentLocale;
}

/** Sets the locale and registers the message registry on the core. */
export function setLocale(locale: string): void {
  currentLocale = SUPPORTED_LOCALES.includes(locale) ? locale : "en";
  setMessageRegistry({
    getString: (bundleName, key) => getLocalizedString(bundleName, key, currentLocale),
  });
}

/** Initializes i18n with the browser/parameter locale (default en). */
export function initMessages(locale: string | null = null): void {
  const resolved = locale ?? guessBrowserLocale();
  setLocale(resolved);
}

/** Detects the best supported locale from navigator.languages. */
export function guessBrowserLocale(): string {
  if (typeof navigator === "undefined") {
    return "en";
  }
  const languages = navigator.languages ?? [navigator.language ?? "en"];
  for (const language of languages) {
    const lang = language.toLowerCase().replace("_", "-");
    if (SUPPORTED_LOCALES.includes(lang)) {
      return lang;
    }
    const primary = lang.split("-")[0]!;
    if (SUPPORTED_LOCALES.includes(primary)) {
      return primary;
    }
  }
  return "en";
}
