/**
 * HomeView interface (port of com.eteks.sweethome3d.viewcontroller.HomeView, GPL v2+).
 * The main view that displays a home.
 */
import type { View } from "./View.js";
import type { Camera } from "../model/Camera.js";

export namespace HomeView {
  /** The actions proposed by the view to the user. */
  export enum ActionType {
    NEW_HOME = "NEW_HOME",
    NEW_HOME_FROM_EXAMPLE = "NEW_HOME_FROM_EXAMPLE",
    CLOSE = "CLOSE",
    OPEN = "OPEN",
    DELETE_RECENT_HOMES = "DELETE_RECENT_HOMES",
    SAVE = "SAVE",
    SAVE_AS = "SAVE_AS",
    SAVE_AND_COMPRESS = "SAVE_AND_COMPRESS",
    PAGE_SETUP = "PAGE_SETUP",
    PRINT_PREVIEW = "PRINT_PREVIEW",
    PRINT = "PRINT",
    PRINT_TO_PDF = "PRINT_TO_PDF",
    PREFERENCES = "PREFERENCES",
    EXIT = "EXIT",
    UNDO = "UNDO",
    REDO = "REDO",
    CUT = "CUT",
    COPY = "COPY",
    PASTE = "PASTE",
    PASTE_TO_GROUP = "PASTE_TO_GROUP",
    PASTE_STYLE = "PASTE_STYLE",
    DELETE = "DELETE",
    SELECT_ALL = "SELECT_ALL",
    SELECT_ALL_AT_ALL_LEVELS = "SELECT_ALL_AT_ALL_LEVELS",
    ADD_HOME_FURNITURE = "ADD_HOME_FURNITURE",
    ADD_FURNITURE_TO_GROUP = "ADD_FURNITURE_TO_GROUP",
    DELETE_HOME_FURNITURE = "DELETE_HOME_FURNITURE",
    MODIFY_FURNITURE = "MODIFY_FURNITURE",
    IMPORT_FURNITURE = "IMPORT_FURNITURE",
    IMPORT_FURNITURE_LIBRARY = "IMPORT_FURNITURE_LIBRARY",
    IMPORT_TEXTURE = "IMPORT_TEXTURE",
    IMPORT_TEXTURES_LIBRARY = "IMPORT_TEXTURES_LIBRARY",
    SORT_HOME_FURNITURE_BY_CATALOG_ID = "SORT_HOME_FURNITURE_BY_CATALOG_ID",
    SORT_HOME_FURNITURE_BY_NAME = "SORT_HOME_FURNITURE_BY_NAME",
    SORT_HOME_FURNITURE_BY_DESCRIPTION = "SORT_HOME_FURNITURE_BY_DESCRIPTION",
    SORT_HOME_FURNITURE_BY_CREATOR = "SORT_HOME_FURNITURE_BY_CREATOR",
    SORT_HOME_FURNITURE_BY_LICENSE = "SORT_HOME_FURNITURE_BY_LICENSE",
    SORT_HOME_FURNITURE_BY_WIDTH = "SORT_HOME_FURNITURE_BY_WIDTH",
    SORT_HOME_FURNITURE_BY_DEPTH = "SORT_HOME_FURNITURE_BY_DEPTH",
    SORT_HOME_FURNITURE_BY_HEIGHT = "SORT_HOME_FURNITURE_BY_HEIGHT",
    SORT_HOME_FURNITURE_BY_X = "SORT_HOME_FURNITURE_BY_X",
    SORT_HOME_FURNITURE_BY_Y = "SORT_HOME_FURNITURE_BY_Y",
    SORT_HOME_FURNITURE_BY_ELEVATION = "SORT_HOME_FURNITURE_BY_ELEVATION",
    SORT_HOME_FURNITURE_BY_ANGLE = "SORT_HOME_FURNITURE_BY_ANGLE",
    SORT_HOME_FURNITURE_BY_LEVEL = "SORT_HOME_FURNITURE_BY_LEVEL",
    SORT_HOME_FURNITURE_BY_MODEL_SIZE = "SORT_HOME_FURNITURE_BY_MODEL_SIZE",
    SORT_HOME_FURNITURE_BY_COLOR = "SORT_HOME_FURNITURE_BY_COLOR",
    SORT_HOME_FURNITURE_BY_TEXTURE = "SORT_HOME_FURNITURE_BY_TEXTURE",
    SORT_HOME_FURNITURE_BY_MOVABILITY = "SORT_HOME_FURNITURE_BY_MOVABILITY",
    SORT_HOME_FURNITURE_BY_TYPE = "SORT_HOME_FURNITURE_BY_TYPE",
    SORT_HOME_FURNITURE_BY_VISIBILITY = "SORT_HOME_FURNITURE_BY_VISIBILITY",
    SORT_HOME_FURNITURE_BY_PRICE = "SORT_HOME_FURNITURE_BY_PRICE",
    SORT_HOME_FURNITURE_BY_VALUE_ADDED_TAX_PERCENTAGE = "SORT_HOME_FURNITURE_BY_VALUE_ADDED_TAX_PERCENTAGE",
    SORT_HOME_FURNITURE_BY_VALUE_ADDED_TAX = "SORT_HOME_FURNITURE_BY_VALUE_ADDED_TAX",
    SORT_HOME_FURNITURE_BY_PRICE_VALUE_ADDED_TAX_INCLUDED = "SORT_HOME_FURNITURE_BY_PRICE_VALUE_ADDED_TAX_INCLUDED",
    SORT_HOME_FURNITURE_BY_DESCENDING_ORDER = "SORT_HOME_FURNITURE_BY_DESCENDING_ORDER",
    DISPLAY_HOME_FURNITURE_CATALOG_ID = "DISPLAY_HOME_FURNITURE_CATALOG_ID",
    DISPLAY_HOME_FURNITURE_NAME = "DISPLAY_HOME_FURNITURE_NAME",
    DISPLAY_HOME_FURNITURE_DESCRIPTION = "DISPLAY_HOME_FURNITURE_DESCRIPTION",
    DISPLAY_HOME_FURNITURE_CREATOR = "DISPLAY_HOME_FURNITURE_CREATOR",
    DISPLAY_HOME_FURNITURE_LICENSE = "DISPLAY_HOME_FURNITURE_LICENSE",
    DISPLAY_HOME_FURNITURE_WIDTH = "DISPLAY_HOME_FURNITURE_WIDTH",
    DISPLAY_HOME_FURNITURE_DEPTH = "DISPLAY_HOME_FURNITURE_DEPTH",
    DISPLAY_HOME_FURNITURE_HEIGHT = "DISPLAY_HOME_FURNITURE_HEIGHT",
    DISPLAY_HOME_FURNITURE_X = "DISPLAY_HOME_FURNITURE_X",
    DISPLAY_HOME_FURNITURE_Y = "DISPLAY_HOME_FURNITURE_Y",
    DISPLAY_HOME_FURNITURE_ELEVATION = "DISPLAY_HOME_FURNITURE_ELEVATION",
    DISPLAY_HOME_FURNITURE_ANGLE = "DISPLAY_HOME_FURNITURE_ANGLE",
    DISPLAY_HOME_FURNITURE_LEVEL = "DISPLAY_HOME_FURNITURE_LEVEL",
    DISPLAY_HOME_FURNITURE_MODEL_SIZE = "DISPLAY_HOME_FURNITURE_MODEL_SIZE",
    DISPLAY_HOME_FURNITURE_COLOR = "DISPLAY_HOME_FURNITURE_COLOR",
    DISPLAY_HOME_FURNITURE_TEXTURE = "DISPLAY_HOME_FURNITURE_TEXTURE",
    DISPLAY_HOME_FURNITURE_MOVABILITY = "DISPLAY_HOME_FURNITURE_MOVABILITY",
    DISPLAY_HOME_FURNITURE_TYPE = "DISPLAY_HOME_FURNITURE_TYPE",
    DISPLAY_HOME_FURNITURE_VISIBILITY = "DISPLAY_HOME_FURNITURE_VISIBILITY",
    DISPLAY_HOME_FURNITURE_PRICE = "DISPLAY_HOME_FURNITURE_PRICE",
    DISPLAY_HOME_FURNITURE_VALUE_ADDED_TAX_PERCENTAGE = "DISPLAY_HOME_FURNITURE_VALUE_ADDED_TAX_PERCENTAGE",
    DISPLAY_HOME_FURNITURE_VALUE_ADDED_TAX = "DISPLAY_HOME_FURNITURE_VALUE_ADDED_TAX",
    DISPLAY_HOME_FURNITURE_PRICE_VALUE_ADDED_TAX_INCLUDED = "DISPLAY_HOME_FURNITURE_PRICE_VALUE_ADDED_TAX_INCLUDED",
    SORT_HOME_FURNITURE_ADDITIONAL_PROPERTY = "SORT_HOME_FURNITURE_ADDITIONAL_PROPERTY",
    DISPLAY_HOME_FURNITURE_ADDITIONAL_PROPERTY = "DISPLAY_HOME_FURNITURE_ADDITIONAL_PROPERTY",
    HOME_FURNITURE_FILTER = "HOME_FURNITURE_FILTER",
    DISPLAY_HOME_FURNITURE_USE_MAGNETISM = "DISPLAY_HOME_FURNITURE_USE_MAGNETISM",
    DISPLAY_HOME_FURNITURE_USE_ALIGNMENT = "DISPLAY_HOME_FURNITURE_USE_ALIGNMENT",
    ZOOM_IN = "ZOOM_IN",
    ZOOM_OUT = "ZOOM_OUT",
    ZOOM_REDEFINE = "ZOOM_REDEFINE",
    PLAN_VIEW = "PLAN_VIEW",
    THREE_D_VIEW = "THREE_D_VIEW",
    TOGGLE_PLAN_ORTHOGRAPHIC_VIEW = "TOGGLE_PLAN_ORTHOGRAPHIC_VIEW",
    TOGGLE_3D_VIEW = "TOGGLE_3D_VIEW",
    MODIFY_WALL = "MODIFY_WALL",
    MODIFY_ROOM = "MODIFY_ROOM",
    MODIFY_DIMENSION_LINE = "MODIFY_DIMENSION_LINE",
    MODIFY_LABEL = "MODIFY_LABEL",
    MODIFY_POLYLINE = "MODIFY_POLYLINE",
    MODIFY_COMPASS = "MODIFY_COMPASS",
    MODIFY_3D_ATTRIBUTES = "MODIFY_3D_ATTRIBUTES",
    MODIFY_OBSERVER_CAMERA = "MODIFY_OBSERVER_CAMERA",
    ADD_WALLS = "ADD_WALLS",
    ADD_ROOMS = "ADD_ROOMS",
    ADD_DIMENSION_LINES = "ADD_DIMENSION_LINES",
    ADD_LABELS = "ADD_LABELS",
    ADD_POLYLINES = "ADD_POLYLINES",
    DELETE_SELECTION = "DELETE_SELECTION",
    ESCAPE = "ESCAPE",
    TOGGLE_PINNING = "TOGGLE_PINNING",
    CANCEL_PINNING = "CANCEL_PINNING",
    TOGGLE_RULERS_VISIBLE = "TOGGLE_RULERS_VISIBLE",
    TOGGLE_GRID_VISIBLE = "TOGGLE_GRID_VISIBLE",
    TOGGLE_GRID_ANGLED = "TOGGLE_GRID_ANGLED",
    TOGGLE_GRID_POINT = "TOGGLE_GRID_POINT",
    TOGGLE_FURNITURE_VISIBLE = "TOGGLE_FURNITURE_VISIBLE",
    TOGGLE_FURNITURE_NAME_VISIBLE = "TOGGLE_FURNITURE_NAME_VISIBLE",
    TOGGLE_LEVELS_VISIBLE = "TOGGLE_LEVELS_VISIBLE",
    TOGGLE_LEVEL_VIEW = "TOGGLE_LEVEL_VIEW",
    TOGGLE_VIEW_FROM_TOP = "TOGGLE_VIEW_FROM_TOP",
    TOGGLE_VIEW_FROM_OBSERVER = "TOGGLE_VIEW_FROM_OBSERVER",
    TOGGLE_X_AXIS_VISIBLE = "TOGGLE_X_AXIS_VISIBLE",
    TOGGLE_Y_AXIS_VISIBLE = "TOGGLE_Y_AXIS_VISIBLE",
    TOGGLE_XY_PLANE_VISIBLE = "TOGGLE_XY_PLANE_VISIBLE",
    TOGGLE_SUN_LIGHT = "TOGGLE_SUN_LIGHT",
    TOGGLE_CEILING_LIGHT = "TOGGLE_CEILING_LIGHT",
    TOGGLE_GROUND_VISIBLE = "TOGGLE_GROUND_VISIBLE",
    TOGGLE_SKY_VISIBLE = "TOGGLE_SKY_VISIBLE",
    TOGGLE_FURNITURE_VISIBLE_IN_3D = "TOGGLE_FURNITURE_VISIBLE_IN_3D",
    TOGGLE_WALLS_VISIBLE_IN_3D = "TOGGLE_WALLS_VISIBLE_IN_3D",
    TOGGLE_ROOMS_VISIBLE_IN_3D = "TOGGLE_ROOMS_VISIBLE_IN_3D",
    TOGGLE_POLYLINES_VISIBLE_IN_3D = "TOGGLE_POLYLINES_VISIBLE_IN_3D",
    TOGGLE_GRID_VISIBLE_IN_3D = "TOGGLE_GRID_VISIBLE_IN_3D",
    TOGGLE_DIMENSION_LINES_VISIBLE_IN_3D = "TOGGLE_DIMENSION_LINES_VISIBLE_IN_3D",
    TOGGLE_LABELS_VISIBLE_IN_3D = "TOGGLE_LABELS_VISIBLE_IN_3D",
    TOGGLE_COMPASS_VISIBLE_IN_3D = "TOGGLE_COMPASS_VISIBLE_IN_3D",
    TOGGLE_BASE_PLAN_LOCKED = "TOGGLE_BASE_PLAN_LOCKED",
    TOGGLE_ALL_LEVELS_SELECTION = "TOGGLE_ALL_LEVELS_SELECTION",
    IMPORT_FURNITURE_LIBRARY_UPDATE = "IMPORT_FURNITURE_LIBRARY_UPDATE",
    IMPORT_TEXTURES_LIBRARY_UPDATE = "IMPORT_TEXTURES_LIBRARY_UPDATE",
    PLUGIN_UPDATE = "PLUGIN_UPDATE",
    IMPORT_LANGUAGE_LIBRARY = "IMPORT_LANGUAGE_LIBRARY",
    STORE_CAMERA = "STORE_CAMERA",
    DELETE_CAMERAS = "DELETE_CAMERAS",
    EXIT_WIZARD = "EXIT_WIZARD",
    SET_DEFAULT_3D_VIEW = "SET_DEFAULT_3D_VIEW",
    SET_DEFAULT_PHOTO_VIEW = "SET_DEFAULT_PHOTO_VIEW",
    SET_DEFAULT_VIDEO_VIEW = "SET_DEFAULT_VIDEO_VIEW",
  }

  export enum SaveAnswer {
    SAVE = "SAVE",
    CANCEL = "CANCEL",
    DO_NOT_SAVE = "DO_NOT_SAVE",
  }

  export enum OpenDamagedHomeAnswer {
    REMOVE_DAMAGED_ITEMS = "REMOVE_DAMAGED_ITEMS",
    REPLACE_DAMAGED_ITEMS = "REPLACE_DAMAGED_ITEMS",
    DO_NOT_OPEN_HOME = "DO_NOT_OPEN_HOME",
  }
}

export interface HomeView extends View {
  setEnabled(actionType: HomeView.ActionType, enabled: boolean): void;
  setActionEnabled(actionKey: string, enabled: boolean): void;
  setUndoRedoName(undoText: string | null, redoText: string | null): void;
  setTransferEnabled(enabled: boolean): void;
  detachView(view: View): void;
  attachView(view: View): void;
  showOpenDialog(): string | null;
  confirmOpenDamagedHome(homeName: string, homeModified: boolean): HomeView.OpenDamagedHomeAnswer;
  showNewHomeFromExampleDialog(): string | null;
  showImportLanguageLibraryDialog(): string | null;
  confirmReplaceLanguageLibrary(languageLibraryName: string): boolean;
  showImportFurnitureLibraryDialog(): string | null;
  confirmReplaceFurnitureLibrary(furnitureLibraryName: string): boolean;
  showImportTexturesLibraryDialog(): string | null;
  confirmReplaceTexturesLibrary(texturesLibraryName: string): boolean;
  confirmReplacePlugin(pluginName: string): boolean;
  showSaveDialog(homeName: string): string | null;
  confirmSave(homeName: string): HomeView.SaveAnswer;
  confirmSaveNewerHome(homeName: string): boolean;
  confirmDeleteCatalogSelection(): boolean;
  confirmExit(): boolean;
  showError(message: string): void;
  showMessage(message: string): void;
  showActionTipMessage(actionTipKey: string): boolean;
  showAboutDialog(): void;
  showPrintDialog(): (() => void) | null;
  showPrintToPDFDialog(homeName: string): string | null;
  printToPDF(pdfFile: string): void;
  showExportToCSVDialog(name: string): string | null;
  exportToCSV(csvName: string): void;
  showExportToSVGDialog(name: string): string | null;
  exportToSVG(svgName: string): void;
  showExportToOBJDialog(homeName: string): string | null;
  exportToOBJ(objFile: string): void;
  showStoreCameraDialog(cameraName: string): string | null;
  showDeletedCamerasDialog(): Camera[];
  isClipboardEmpty(): boolean;
}
